### PR TITLE
docs: use the latest CoC version

### PR DESCRIPTION
**Pull request by Panquesito7**
## 👨‍💻 Changes proposed

- Use the latest code of conduct version.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

None.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey,

GitHub is still providing 2.0. Where did you find those chances? Any resources?

**Comment by Panquesito7** [comment]
All the versions can be found here: https://www.contributor-covenant.org/

**Review by Pradumnasaraf — COMMENTED** [review]
> All the versions can be found here: https://www.contributor-covenant.org/

Yes, but I mean when I create a new COC, GitHub is still proving me with a 2.0 template.
Screenshot 2023-04-27 at 2 10 15 PM

**Comment by Panquesito7** [comment]
> > All the versions can be found here: https://www.contributor-covenant.org/
>
> Yes, but I mean when I create a new COC, GitHub is still proving me with a 2.0 template.

Yes, GitHub still uses 2.0, but I think it's best to use 2.1, IMO.
It's up to you. Feel free to either merge or close this PR. 🙂

**Comment by Pradumnasaraf** [comment]
Hey,

I will stick with what the GitHub is sticking with right now. We will see in future. Thank you for your time.

**Pull request closed without merging**
