### PR TITLE
Adding the version command

### LINKED ISSUE #13: [FEATURE] Add a version command or flag
### Description

The command will out the current CLI version in the terminal

### PR DESCRIPTION
**Pull request by pmuls99**
## 🛠️ Fixes Issue
Closes #13 
## 👨‍💻 Changes proposed
Added a new file for version.yml and version.go.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Thanks for the PR. I think there is an issue, the viper will always look for the `version.yml` file in. What I mean is that if we run an executable outside of the project anywhere in the system, it will always look for that file. I hope you get it.

> Image for reference. I am running the executable without having the version file.
Screenshot 2023-05-27 at 2 04 26 AM

I am thinking about how we can work around for that.

**Comment by pmuls99** [comment]
Oh yes.
Inform if you come up with a solution, I will also be looking out for one.

**Review by Pradumnasaraf — COMMENTED** [review]
Hey, 

I found a solution. I look at the civo/cli  [implementation](https://github.com/civo/cli/blob/c703ac0cba31719e8132711b7dc73f7f73c0e873/common/common.go#L50) they are using https://github.com/tcnksm/go-latest#github-tag. I think this might do our job.

**Comment by pmuls99** [comment]
Yaa looks like it does our job. Will implement.

**Comment by Pradumnasaraf** [comment]
> Yaa looks like it does our job. Will implement.

Hey, If you need help. Do let me know.

**Comment by Pradumnasaraf** [comment]
Hey, Are you still working on this?

**Comment by Pradumnasaraf** [comment]
Hey, @pmuls99. I am waiting for your fix as this PR is opened for more than 3 weeks. Let me know if you need any help.

**Comment by Pradumnasaraf** [comment]
Closing PR. No response from the contributor.

**Pull request closed without merging**
